// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3o4ag_66gwlz5iZAbGmpTTr-TNoXCaps',
    appId: '1:969392343439:web:a7888ba846cd3c43be63fa',
    messagingSenderId: '969392343439',
    projectId: 'todoapp-32ebc',
    authDomain: 'todoapp-32ebc.firebaseapp.com',
    storageBucket: 'todoapp-32ebc.appspot.com',
    measurementId: 'G-V62WF618J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjkWGJG2qkGxAe2o3w6sN1VeWtl_WCvzM',
    appId: '1:969392343439:android:2b8a17bdfed67d53be63fa',
    messagingSenderId: '969392343439',
    projectId: 'todoapp-32ebc',
    storageBucket: 'todoapp-32ebc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfibEYz4cqrV3x0v9PQW6R3V6cf1aZ4Is',
    appId: '1:969392343439:ios:b08e542133bcbd69be63fa',
    messagingSenderId: '969392343439',
    projectId: 'todoapp-32ebc',
    storageBucket: 'todoapp-32ebc.appspot.com',
    iosBundleId: 'com.expertappdevs.todoapp.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfibEYz4cqrV3x0v9PQW6R3V6cf1aZ4Is',
    appId: '1:969392343439:ios:b08e542133bcbd69be63fa',
    messagingSenderId: '969392343439',
    projectId: 'todoapp-32ebc',
    storageBucket: 'todoapp-32ebc.appspot.com',
    iosBundleId: 'com.expertappdevs.todoapp.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3o4ag_66gwlz5iZAbGmpTTr-TNoXCaps',
    appId: '1:969392343439:web:af5621cf5e6f8840be63fa',
    messagingSenderId: '969392343439',
    projectId: 'todoapp-32ebc',
    authDomain: 'todoapp-32ebc.firebaseapp.com',
    storageBucket: 'todoapp-32ebc.appspot.com',
    measurementId: 'G-49M1HW8QZP',
  );
}
